# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-24 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=32, null=True, verbose_name='地址')),
                ('user_grade', models.CharField(max_length=32, null=True, verbose_name='等级')),
                ('user_phone', models.CharField(max_length=16, null=True, verbose_name='电话')),
                ('Due_time', models.CharField(max_length=16, null=True, verbose_name='到期时间')),
                ('user_stay_years', models.CharField(max_length=16, null=True, verbose_name='年限')),
                ('user_gender', models.CharField(max_length=4, verbose_name='性别')),
                ('user_age', models.IntegerField(null=True, verbose_name='编号')),
                ('user_number', models.CharField(max_length=16, null=True, verbose_name='电话')),
                ('user_remarks', models.CharField(max_length=32, null=True, verbose_name='备注')),
                ('user_recentip', models.CharField(max_length=16, null=True, verbose_name='最近的ip')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
