# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mould',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.TextField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('tieba_num', models.IntegerField()),
                ('blog_num', models.IntegerField()),
                ('sensitive', models.IntegerField()),
                ('no_sensitive', models.IntegerField()),
                ('mould', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Mould')),
            ],
        ),
    ]
