# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='舆情简报', max_length=30),
        ),
    ]
